### ISSUE TITLE
problem with unregistering a box which was already removed from vagrant

### ISSUE THREAD

**Issue by Ashalynd** [StarterSquad/prudentia#12]
How to reproduce:

1. Start prudentia, register and provision an instance in vagrant. Quit.

2. Destroy an instance by ID in vagrant.

3. Start prudentia, try to destroy an instance which was just deleted in vagrant. It complains that there is no ID so nothing is removed.

4. Try to register another instance with the same playbook (and the same name as the deleted instance). An alternative name is offered, because the original instance is still assumed to exist. Forcing the instance name doesn't help either. (Current workaround: remove the entry from  ~/prudentia/envs/vagrant/boxes.json )

**Comment by TizianoPerrucci** [comment]
@Ashalynd sorry for the little delay, the solution is to simply use `unregister`. Using the `unregister` action is more convinient to use because it will ask you to destroy the instance as well. Hope this helps.
