### ISSUE TITLE
nodejs module install or update

### ISSUE THREAD

**Issue by alexsyo** [StarterSquad/prudentia#53]
it would be useful to allow the script to update the node version if it is different from the one installed

**Comment by TizianoPerrucci** [comment]
Hi,

you can override the nvm and node version with the following:

```
  nvm_version: v0.33.2
  node_version: v6.11.2
  node_path: "{{ansible_env.HOME}}/.nvm/versions/node/{{node_version}}"
```

**Comment by alexsyo** [comment]
thank you, I was passing the version without the "v" character.

can be closed

**Comment by TizianoPerrucci** [comment]
you're welcome
