### ISSUE TITLE
Support for ansible 2.4.0.0

### ISSUE THREAD

**Issue by Voronenko** [StarterSquad/prudentia#54]
Api has changed, prudentia no longer is able to run playbooks

**Comment by TizianoPerrucci** [comment]
I've just tried to upgrade to Ansible 2.4.0 and tests run fine.
How can i reproduce your issue?

**Comment by TizianoPerrucci** [comment]
Never mind, I see the problem https://travis-ci.org/StarterSquad/prudentia

**Comment by TizianoPerrucci** [comment]
@Voronenko do you have time for testing locally #56 and give me some feedback?
you can follow those instructions https://github.com/StarterSquad/prudentia#development

**Comment by Voronenko** [comment]
Yes, in foreseen reasonable time. Will add to backlog
