### ISSUE TITLE
Run "npm cache clean" if "npm install/update" failed

### ISSUE THREAD

**Issue by dmitryevseev** [StarterSquad/prudentia#7]
In some scenarios `npm install/update` can be blocked by issues with cache.

If command fails you need to run `npm cache clean` and retry command again.

[If you give me some time, I can give it a try and create a PR for this one]

**Comment by TizianoPerrucci** [comment]
@dmitryevseev Prudentia is not responsible to npm packages updates or install. We use to have a clean_build bash script that would be used by the CI for building, so that script should be changed.
